namespace JS.Base.WS.API.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class updatevariables : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.ClassroomClimates", "EfficiencyValueA", c => c.String());
            AddColumn("dbo.ClassroomClimates", "EfficiencyColourA", c => c.String());
            AddColumn("dbo.ClassroomClimates", "EfficiencyValueB", c => c.String());
            AddColumn("dbo.ClassroomClimates", "EfficiencyColourB", c => c.String());
            AddColumn("dbo.ClassroomClimates", "EfficiencyValueC", c => c.String());
            AddColumn("dbo.ClassroomClimates", "EfficiencyColourC", c => c.String());
            AddColumn("dbo.ClassroomClimates", "EfficiencyTotalValue", c => c.String());
            AddColumn("dbo.ClassroomClimates", "EfficiencyTotalColour", c => c.String());
            AddColumn("dbo.ClassroomClimates", "EfficiencyEvaluateFactor", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyValueA", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyColourA", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyValueB", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyColourB", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyValueC", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyColourC", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyTotalValue", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyTotalColour", c => c.String());
            AddColumn("dbo.ContentDomains", "EfficiencyEvaluateFactor", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyValueA", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyColourA", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyValueB", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyColourB", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyValueC", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyColourC", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyTotalValue", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyTotalColour", c => c.String());
            AddColumn("dbo.EvaluationProcesses", "EfficiencyEvaluateFactor", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyValueA", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyColourA", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyValueB", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyColourB", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyValueC", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyColourC", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyTotalValue", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyTotalColour", c => c.String());
            AddColumn("dbo.PedagogicalResources", "EfficiencyEvaluateFactor", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyValueA", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyColourA", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyValueB", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyColourB", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyValueC", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyColourC", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyTotalValue", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyTotalColour", c => c.String());
            AddColumn("dbo.Plannings", "EfficiencyEvaluateFactor", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyValueA", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyColourA", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyValueB", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyColourB", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyValueC", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyColourC", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyTotalValue", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyTotalColour", c => c.String());
            AddColumn("dbo.ReflectionPractices", "EfficiencyEvaluateFactor", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyValueA", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyColourA", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyValueB", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyColourB", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyValueC", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyColourC", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyTotalValue", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyTotalColour", c => c.String());
            AddColumn("dbo.RelationFatherMothers", "EfficiencyEvaluateFactor", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyValueA", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyColourA", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyValueB", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyColourB", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyValueC", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyColourC", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyTotalValue", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyTotalColour", c => c.String());
            AddColumn("dbo.StrategyActivities", "EfficiencyEvaluateFactor", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.StrategyActivities", "EfficiencyEvaluateFactor");
            DropColumn("dbo.StrategyActivities", "EfficiencyTotalColour");
            DropColumn("dbo.StrategyActivities", "EfficiencyTotalValue");
            DropColumn("dbo.StrategyActivities", "EfficiencyColourC");
            DropColumn("dbo.StrategyActivities", "EfficiencyValueC");
            DropColumn("dbo.StrategyActivities", "EfficiencyColourB");
            DropColumn("dbo.StrategyActivities", "EfficiencyValueB");
            DropColumn("dbo.StrategyActivities", "EfficiencyColourA");
            DropColumn("dbo.StrategyActivities", "EfficiencyValueA");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyEvaluateFactor");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyTotalColour");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyTotalValue");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyColourC");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyValueC");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyColourB");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyValueB");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyColourA");
            DropColumn("dbo.RelationFatherMothers", "EfficiencyValueA");
            DropColumn("dbo.ReflectionPractices", "EfficiencyEvaluateFactor");
            DropColumn("dbo.ReflectionPractices", "EfficiencyTotalColour");
            DropColumn("dbo.ReflectionPractices", "EfficiencyTotalValue");
            DropColumn("dbo.ReflectionPractices", "EfficiencyColourC");
            DropColumn("dbo.ReflectionPractices", "EfficiencyValueC");
            DropColumn("dbo.ReflectionPractices", "EfficiencyColourB");
            DropColumn("dbo.ReflectionPractices", "EfficiencyValueB");
            DropColumn("dbo.ReflectionPractices", "EfficiencyColourA");
            DropColumn("dbo.ReflectionPractices", "EfficiencyValueA");
            DropColumn("dbo.Plannings", "EfficiencyEvaluateFactor");
            DropColumn("dbo.Plannings", "EfficiencyTotalColour");
            DropColumn("dbo.Plannings", "EfficiencyTotalValue");
            DropColumn("dbo.Plannings", "EfficiencyColourC");
            DropColumn("dbo.Plannings", "EfficiencyValueC");
            DropColumn("dbo.Plannings", "EfficiencyColourB");
            DropColumn("dbo.Plannings", "EfficiencyValueB");
            DropColumn("dbo.Plannings", "EfficiencyColourA");
            DropColumn("dbo.Plannings", "EfficiencyValueA");
            DropColumn("dbo.PedagogicalResources", "EfficiencyEvaluateFactor");
            DropColumn("dbo.PedagogicalResources", "EfficiencyTotalColour");
            DropColumn("dbo.PedagogicalResources", "EfficiencyTotalValue");
            DropColumn("dbo.PedagogicalResources", "EfficiencyColourC");
            DropColumn("dbo.PedagogicalResources", "EfficiencyValueC");
            DropColumn("dbo.PedagogicalResources", "EfficiencyColourB");
            DropColumn("dbo.PedagogicalResources", "EfficiencyValueB");
            DropColumn("dbo.PedagogicalResources", "EfficiencyColourA");
            DropColumn("dbo.PedagogicalResources", "EfficiencyValueA");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyEvaluateFactor");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyTotalColour");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyTotalValue");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyColourC");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyValueC");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyColourB");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyValueB");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyColourA");
            DropColumn("dbo.EvaluationProcesses", "EfficiencyValueA");
            DropColumn("dbo.ContentDomains", "EfficiencyEvaluateFactor");
            DropColumn("dbo.ContentDomains", "EfficiencyTotalColour");
            DropColumn("dbo.ContentDomains", "EfficiencyTotalValue");
            DropColumn("dbo.ContentDomains", "EfficiencyColourC");
            DropColumn("dbo.ContentDomains", "EfficiencyValueC");
            DropColumn("dbo.ContentDomains", "EfficiencyColourB");
            DropColumn("dbo.ContentDomains", "EfficiencyValueB");
            DropColumn("dbo.ContentDomains", "EfficiencyColourA");
            DropColumn("dbo.ContentDomains", "EfficiencyValueA");
            DropColumn("dbo.ClassroomClimates", "EfficiencyEvaluateFactor");
            DropColumn("dbo.ClassroomClimates", "EfficiencyTotalColour");
            DropColumn("dbo.ClassroomClimates", "EfficiencyTotalValue");
            DropColumn("dbo.ClassroomClimates", "EfficiencyColourC");
            DropColumn("dbo.ClassroomClimates", "EfficiencyValueC");
            DropColumn("dbo.ClassroomClimates", "EfficiencyColourB");
            DropColumn("dbo.ClassroomClimates", "EfficiencyValueB");
            DropColumn("dbo.ClassroomClimates", "EfficiencyColourA");
            DropColumn("dbo.ClassroomClimates", "EfficiencyValueA");
        }
    }
}
