// <auto-generated />
namespace JS.Base.WS.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addPurchaseTransactions02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPurchaseTransactions02));
        
        string IMigrationMetadata.Id
        {
            get { return "202108170313219_add PurchaseTransactions 02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
